### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ashencloud** [blowfishpro/B9-Aerospace#23]
your wheels don't retract 
i cant right click the "blocks" to change their type
cargo bays dont close 
some parts don't attach 
and for the last one, i cant say it but you can watch my video on it here
https://www.youtube.com/watch?v=uMxSuS7v4pk

**Comment by blowfishpro** [comment]
It sounds like you have something installed incorrectly.  The fact that you even have wheels suggests that you're on an old version of B9, since the wheels were broken by KSP 1.1 and thus removed.  Try reinstalling B9 and all of its dependencies from the latest download (assuming you are on KSP 1.1.3), and see if the issues persist.  If that doesn't fix it, please read this topic:

http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

It will tell you how to find and upload KSP's log - from reading the log I can probably identify what the issue is.

**Comment by ashencloud** [comment]
thanks for the answer but, the one i downloaded was the latest, (i think) well ill try downloading it again

**Comment by ashencloud** [comment]
ok, so i clicked the blue button "download from github" now what do i do? because they're different options

**Comment by ashencloud** [comment]
got it to work thanks for your time :D
