### ISSUE TITLE
Game crashes during startup

### ISSUE THREAD

**Issue by Monniasza** [blowfishpro/B9-Aerospace#89]
[error.log](https://github.com/blowfishpro/B9-Aerospace/files/3199136/error.log)
I gave you crash log, game crashes on startup.

**Comment by blowfishpro** [comment]
Need the full output_log.txt to see the cause of the crash.  The crash log doesn’t provide any useful info.

And what makes you think B9 is the cause of this crash?

**Comment by blowfishpro** [comment]
Well you have some very old plugins installed.  I’m not exactly sure what’s causing the crash but I think it’s related to that.  Definitely not B9 causing the crash.  I recommend starting with a clean install and copying KSP outside of Steam’s install directory so that you don’t end up with a broken install after KSP updates it.

**Comment by blowfishpro** [comment]
Also you don’t have most of the dependencies for B9 even installed.  They’re all listed in the first page of the forum thread.

**Comment by blowfishpro** [comment]
And you have two copies of B9, including the ancient 5.2.8
